<script setup>
import { computed } from 'vue'; import { Package, TriangleAlert, ArrowDownToLine, ArrowUpFromLine } from 'lucide-vue-next'; import PageHeader from '../components/PageHeader.vue'; import {state} from '../data/store'
const low=computed(()=>state.products.filter(p=>p.qty<=p.min)); const entries=computed(()=>state.movements.filter(m=>m.type==='ENTRADA').reduce((a,m)=>a+m.qty,0)); const exits=computed(()=>state.movements.filter(m=>m.type==='SAÍDA').reduce((a,m)=>a+m.qty,0)); const recent=computed(()=>[...state.movements].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5));
const fmt=d=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(d))
</script>
<template><PageHeader title="Dashboard" subtitle="Visão geral do seu estoque."/>
<div class="stats-grid"><div class="stat-card"><span class="stat-icon"><Package/></span><div><small>Produtos cadastrados</small><strong>{{state.products.length}}</strong></div></div><div class="stat-card warning"><span class="stat-icon"><TriangleAlert/></span><div><small>Estoque baixo</small><strong>{{low.length}}</strong></div></div><div class="stat-card success"><span class="stat-icon"><ArrowDownToLine/></span><div><small>Total de entradas</small><strong>{{entries}}</strong></div></div><div class="stat-card info"><span class="stat-icon"><ArrowUpFromLine/></span><div><small>Total de saídas</small><strong>{{exits}}</strong></div></div></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-title"><div><h2>Movimentações recentes</h2><p>Últimas entradas e saídas registradas.</p></div><router-link to="/movimentacoes" class="text-link">Ver todas</router-link></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Tipo</th><th>Qtd.</th><th>Data</th></tr></thead><tbody><tr v-for="m in recent" :key="m.id"><td><b>{{m.product}}</b></td><td><span class="badge" :class="m.type==='ENTRADA'?'badge-success':'badge-danger'">{{m.type}}</span></td><td>{{m.qty}}</td><td>{{fmt(m.date)}}</td></tr></tbody></table></div></section>
<section class="panel"><div class="panel-title"><div><h2>Atenção necessária</h2><p>Produtos no estoque mínimo ou abaixo.</p></div></div><div class="low-list"><div v-for="p in low" :key="p.id" class="low-item"><div><b>{{p.name}}</b><small>{{p.category}}</small></div><div class="low-qty"><strong>{{p.qty}}</strong><small>mín. {{p.min}}</small></div></div><div v-if="!low.length" class="empty">Tudo certo por aqui.</div></div></section></div>
</template>
