<script setup>
import { ref, computed } from 'vue'; import { Plus, Search, Pencil, Trash2 } from 'lucide-vue-next'; import PageHeader from '../components/PageHeader.vue'; import Modal from '../components/Modal.vue'; import {state,persist} from '../data/store'
const q=ref(''), show=ref(false), editId=ref(null); const form=ref({name:'',category:'',supplier:'',price:'',qty:'',min:''}); const filtered=computed(()=>state.products.filter(p=>(p.name+' '+p.category+' '+p.supplier).toLowerCase().includes(q.value.toLowerCase())))
function open(p=null){editId.value=p?.id??null;form.value=p?{...p}:{name:'',category:state.categories[0]?.name||'',supplier:state.suppliers[0]?.name||'',price:'',qty:'',min:''};show.value=true}
function save(){if(!form.value.name)return; const data={...form.value,price:Number(form.value.price)||0,qty:Number(form.value.qty)||0,min:Number(form.value.min)||0,active:true}; if(editId.value){Object.assign(state.products.find(p=>p.id===editId.value),data)}else state.products.push({...data,id:Date.now()});persist();show.value=false}
function remove(p){if(confirm(`Excluir ${p.name}?`)){state.products.splice(state.products.indexOf(p),1);persist()}}
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
</script>
<template><PageHeader title="Produtos" subtitle="Cadastre, consulte e atualize os produtos do estoque."><button class="btn btn-primary" @click="open()"><Plus :size="18"/>Novo produto</button></PageHeader><section class="panel"><div class="toolbar"><div class="search"><Search :size="18"/><input v-model="q" placeholder="Buscar por produto, categoria ou fornecedor..."/></div></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Fornecedor</th><th>Preço</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="p in filtered" :key="p.id"><td><b>{{p.name}}</b></td><td>{{p.category}}</td><td>{{p.supplier}}</td><td>{{money(p.price)}}</td><td><b :class="{'danger-text':p.qty<=p.min}">{{p.qty}}</b> <small>/ mín. {{p.min}}</small></td><td><span class="badge" :class="p.active?'badge-success':'badge-muted'">{{p.active?'Ativo':'Inativo'}}</span></td><td class="actions"><button class="icon-btn" @click="open(p)"><Pencil :size="17"/></button><button class="icon-btn danger-text" @click="remove(p)"><Trash2 :size="17"/></button></td></tr></tbody></table></div></section>
<Modal v-if="show" :title="editId?'Editar produto':'Cadastrar produto'" @close="show=false"><form class="form-grid" @submit.prevent="save"><div class="field full"><label>Nome do produto</label><input v-model="form.name" required/></div><div class="field"><label>Categoria</label><select v-model="form.category"><option v-for="c in state.categories" :key="c.id">{{c.name}}</option></select></div><div class="field"><label>Fornecedor</label><select v-model="form.supplier"><option v-for="s in state.suppliers" :key="s.id">{{s.name}}</option></select></div><div class="field"><label>Preço (R$)</label><input v-model="form.price" type="number" min="0" step="0.01"/></div><div class="field"><label>Quantidade</label><input v-model="form.qty" type="number" min="0"/></div><div class="field"><label>Estoque mínimo</label><input v-model="form.min" type="number" min="0"/></div><div class="modal-actions full"><button type="button" class="btn btn-secondary" @click="show=false">Cancelar</button><button class="btn btn-primary">Salvar produto</button></div></form></Modal></template>
